name: Rust

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          components: clippy
      - name: Build | Lint
        run: cargo clippy
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
      - name: Build | Compile
        run: cargo check
  test:
    name: Test
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        # - macOS-latest
        rust:
          # - stable
          # - beta
          - nightly
    runs-on: ${{ matrix.os }}
    needs: [compile]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}
      - name: Build | Compile
        run: cargo test
  package:
    name: Package
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        # - macOS-latest
        rust:
          # - stable
          # - beta
          - nightly
    runs-on: ${{ matrix.os }}
    needs: [test]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        shell: bash
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust }}

      - name: Build | Compile
        run: cargo build --release --locked

      - name: Create Archive
        shell: bash
        if: matrix.target.os != 'windows-latest'
        run: |
          mkdir -p target/package/
          cp target/release/octodeps target/package/
          cp -r static target/package/
          cp -r templates target/package/
          find target/package
          tar czvf octodeps-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target.target }}.tar.gz -C target/package/ .
      - name: Create Archive (Windows)
        if: matrix.target.os == 'windows-latest'
        run: |
          mkdir target/package/
          Copy-Item -Path "target/release/octodeps" -Destination "target/package"
          Copy-Item -Path "static" -Destination "target/package" -Recurse
          Copy-Item -Path "templates" -Destination "target/package" -Recurse
          cd target/package
          7z.exe a ../octodeps-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target.target }}.zip .

      - name: Upload assets
        uses: softprops/action-gh-release@v1
        if: matrix.target.os != 'windows-latest'
        with:
          files: |
            octodeps-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target.target }}.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload assets (Windows)
        uses: softprops/action-gh-release@v1
        if: matrix.target.os == 'windows-latest'
        with:
          files: |
            octodeps-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target.target }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}